image: fpco/stack-build:lts-8.15

stages:
  - build
 
variables:
  STACK_OPTS: "--system-ghc"
  STACK_ROOT: "${CI_PROJECT_DIR}/.stack"

build:
  stage: build
  script:
    - mkdir target
    - stack setup --system-ghc
    - stack install --local-bin-path target --system-ghc

cache:
  paths:
    - .stack
    - .stack-work
    - target
