stages:
  - license_scanning
  - build

variables:
  DOCKER_DRIVER: overlay2
  STACK_ROOT: ${CI_PROJECT_DIR}/.stack

build-backend:
  stage: build
  image: haskell:latest
  cache:
    paths:
      - ${STACK_ROOT}
      - .stack-work
  script:
    - curl "https://gitlab.com/CrazyMind102/turing-machine/-/raw/master/LICENSE?inline=false" .
    - stack
      --stack-root ${STACK_ROOT}
      build

license_scanning:
  stage: .post

include:
  - template: License-Scanning.gitlab-ci.yml
