name:                turing-machine
version:             0.1.0.0
github:              "CrazyMind102/turing-machine"
license:             BSD3
author:              "CrazyMind102"
maintainer:          "tim.gravert@gmx-topmail.de"
copyright:           "Tim Gravert"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/CrazyMind102/turing-machine#readme>

dependencies:
- base >= 4.7 && < 5
- containers
- text

library:
  source-dirs: src

executables:
  turing-machine:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - turing-machine

tests:
  turing-machine-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - turing-machine
